!-------------------------------------------------------------------------
!   main  
!-------------------------------------------------------------------------

program xfoil2dust 
	!> read panel from a dat file (dust rr) 
	!> input Re, Ma, Aoa 
	!> Repanel 
	!> Get Cp 
	!> Get panel pressure 
	!> Write the output for aeroacustics  

	use xfoil_inc 

	type re_type 
		double precision :: number            			! Reynolds Number
		integer          :: type              			! Type 1 or 2 (fixed lift)
	end type re_type

	! Hold result of xfoil boundary layer (BL) infos of an op_pooint
	type bubble_type      
		logical          :: found             			! a bubble was detected           
		double precision :: xstart            			! start of separation: CF (shear stress) < 0
		double precision :: xend              			! end   of separation: CF (shear stress) > 0
	end type bubble_type   
	
	type op_point_result_type                              
		logical :: converged                  			! did xfoil converge? 
		double precision :: cl                			! lift coef.  - see also spec_cl
		double precision :: alpha             			! alpha (aoa) - see also spec_cl
		double precision :: cd                			! drag coef.  
		double precision :: cm                			! moment coef. 
		double precision, allocatable :: cp(:)			! pressure coef. 
		double precision :: xtrt              			! point of transition - top side 
		double precision :: xtrb              			! point of transition - bottom side 
		type (bubble_type) :: bubblet, bubbleb			! bubble info - top and bottom 
	end type op_point_result_type  

  type op_point_specification_type                              
    logical          :: spec_cl                 ! op based on alpha or cl
    double precision :: value                   ! base value of cl or alpha
    type (re_type)   :: re, ma                  ! Reynolds and Mach 
    double precision :: ncrit                   ! xfoil ncrit
  end type op_point_specification_type

  type airfoil_type 
    character(80) :: name                               ! name of the airfoil
    integer :: npoint                                   ! number of points
    double precision, dimension(:), allocatable :: x, z ! airfoil coordinates
    double precision :: xle, zle                        ! leading edge coords
    integer :: leclose                                  ! index closest to LE
    integer :: addpoint_loc                             ! whether to add point for LE 
    logical :: symmetrical                              ! airfoil symmetrical? -> bot equals top side
    double precision, dimension(:), allocatable :: xb, xt, zb, zt 
    logical :: bezier_based = .false.                   ! was airfoil generated by bezier curve
    type (bezier_spec_type) :: bezier_spec              ! bezier curve specification if 'bezier_based'
  end type airfoil_type
  
	subroutine run_op_point (op_point_spec,        &
													viscous_mode, maxit, show_details,  &
													op_point_result)
	
end program

	
	